# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSYa3ht20Q3vVi4XSvugTb0OAfiLIULI

:

## Step 1 — Install dependencies

This notebook uses the official Hugging Face `train_controlnet.py` script.  
The script contains the internal training loop: data loading, loss calculation, backpropagation, optimizer step, and saving.

> If Colab asks you to restart after installation, restart and continue from the next cell.
"""

!pip install -q diffusers transformers accelerate safetensors opencv-python pillow
!pip install -q torch torchvision torchaudio

!git clone https://github.com/huggingface/diffusers

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/diffusers/examples/controlnet
!pip install -q -r requirements.txt

"""## Step 2 — Mount Google Drive and extract dataset

Your dataset should be a zip file containing:

```text
wedding_data/
├── images/
├── conditioning_images/   # or edges/ before automatic rename
└── metadata.csv
```

The CSV must contain:

```text
image, conditioning_image, caption
```

"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile, os

zip_path = "/content/wedding_data.zip"
extract_path = "/content/wedding_data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("done")
print("done")

import os

if os.path.exists("/content/wedding_data/edges") and not os.path.exists("/content/wedding_data/conditioning_images"):
    os.rename("/content/wedding_data/edges", "/content/wedding_data/conditioning_images")

print("done")

"""### Read metadata"""

import pandas as pd

df = pd.read_csv("/content/wedding_data/metadata.csv")
print(df.head())

"""## 5. Dataset visualization
The model learns from image + edge map + caption. These examples show the target image and its structural condition.
"""



import matplotlib.pyplot as plt
from PIL import Image
import textwrap

samples = df.sample(min(4, len(df)), random_state=42).reset_index(drop=True)
fig, axes = plt.subplots(len(samples), 2, figsize=(12, 4 * len(samples)))
fig.suptitle("Dataset Samples: Original Image and Edge Condition", fontsize=16, fontweight="bold")

if len(samples) == 1:
    axes = [axes]

for i, row in samples.iterrows():
    img = Image.open(os.path.join(DATASET_DIR, row["image"])).convert("RGB")
    edge = Image.open(os.path.join(DATASET_DIR, row["conditioning_image"])).convert("RGB")

    axes[i][0].imshow(img)
    axes[i][0].set_title("Original Wedding Image")
    axes[i][0].axis("off")

    axes[i][1].imshow(edge)
    axes[i][1].set_title("Canny Edge Condition")
    axes[i][1].axis("off")

plt.tight_layout()
plt.show()

print("Example captions:")
for i, row in samples.iterrows():
    print(f"Sample {i+1}:", textwrap.fill(str(row["caption"]), width=100))

"""## 8. Data augmentation demonstration
Because the dataset is small, augmentation can reduce overfitting. For ControlNet, the image and edge map must stay aligned.
"""



from torchvision import transforms

image_augmentation = transforms.Compose([
    transforms.Resize((512, 512)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.10),
])

edge_augmentation = transforms.Compose([
    transforms.Resize((512, 512)),
    transforms.RandomHorizontalFlip(p=0.5),
])

row_aug = df.iloc[0]
img = Image.open(os.path.join(DATASET_DIR, row_aug["image"])).convert("RGB")
edge = Image.open(os.path.join(DATASET_DIR, row_aug["conditioning_image"])).convert("RGB")

fig, axes = plt.subplots(1, 4, figsize=(16,4))
axes[0].imshow(img); axes[0].set_title("Original")
axes[1].imshow(edge); axes[1].set_title("Original Edge")
axes[2].imshow(image_augmentation(img)); axes[2].set_title("Augmented Image")
axes[3].imshow(edge_augmentation(edge)); axes[3].set_title("Augmented Edge")
for ax in axes: ax.axis("off")
plt.tight_layout()
plt.show()

import pandas as pd

csv_path = "/content/wedding_data/metadata.csv"
df = pd.read_csv(csv_path)

df["conditioning_image"] = df["conditioning_image"].str.replace("edges/", "conditioning_images/", regex=False)

df.to_csv(csv_path, index=False)
print(df.head())

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/diffusers
!pip install -e .

"""## **Training**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/diffusers/examples/controlnet

!accelerate launch train_controlnet.py \
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
  --controlnet_model_name_or_path="lllyasviel/control_v11p_sd15_canny" \
  --output_dir="/content/controlnet-wedding10" \
  --resolution=512 \
  --learning_rate=1e-5 \
  --train_batch_size=1 \
  --num_train_epochs=10 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=50

import os
print(os.listdir("/content/controlnet-wedding5"))

import torch
import pandas as pd
from PIL import Image
from diffusers import ControlNetModel, StableDiffusionControlNetPipeline

controlnet = ControlNetModel.from_pretrained(
    "/content/controlnet-wedding10",
    torch_dtype=torch.float16
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16
).to("cuda")

df = pd.read_csv("/content/wedding_data/metadata.csv")

# Choose another image here
row = df.iloc[5]

edge_image = Image.open("/content/wedding_data/" + row["conditioning_image"]).convert("RGB").resize((512, 512))
prompt = row["caption"]

result = pipe(
    prompt=prompt,
    image=edge_image,
    num_inference_steps=20
).images[0]

result.save("/content/fine_tuned_test_output.png")
result

save_path = "/content/drive/MyDrive/controlnet-wedding10"

controlnet.save_pretrained(save_path)

print("Modèle sauvegardé ici :", save_path)